// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "Jordan-Tech-Companies/web/templates/layouts"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container-lg\"><section class=\"hero p-5 mb-5 bg-light rounded text-center border\"><h1 class=\"display-4 fw-bold\">JoTech Directory</h1><p class=\"lead\">Discover tech companies, startups, and innovators across Jordan.</p><div class=\"mt-4\"><a href=\"/companies\" class=\"btn btn-primary btn-lg px-4 me-2\">Browse Directory</a> <a href=\"/about\" class=\"btn btn-outline-secondary btn-lg px-4\">Learn More</a></div></section><section class=\"mb-5\"><h2 class=\"text-center mb-4\">Why Use JoTech?</h2><div class=\"row g-4 text-center\"><div class=\"col-md-4\"><div class=\"card h-100 shadow-sm\"><div class=\"card-body\"><h5 class=\"card-title fw-bold\">Easy Discovery</h5><p class=\"card-text\">Search and filter companies by size, location, and focus.</p></div></div></div><div class=\"col-md-4\"><div class=\"card h-100 shadow-sm\"><div class=\"card-body\"><h5 class=\"card-title fw-bold\">Connect & Network</h5><p class=\"card-text\">Find the right people and companies to work with.</p></div></div></div><div class=\"col-md-4\"><div class=\"card h-100 shadow-sm\"><div class=\"card-body\"><h5 class=\"card-title fw-bold\">Market Insights</h5><p class=\"card-text\">Understand the landscape of Jordan's tech ecosystem.</p></div></div></div></div></section><section class=\"mb-5 bg-light p-5 rounded border text-center\"><h2 class=\"mb-4\">By The Numbers</h2><div class=\"row\"><div class=\"col-md-4\"><h3>100+</h3><p class=\"text-muted\">Companies</p></div><div class=\"col-md-4\"><h3>10+</h3><p class=\"text-muted\">Users</p></div><div class=\"col-md-4\"><h3>3+</h3><p class=\"text-muted\">Connections</p></div></div></section></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base("Home").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
